[package]
name = "bmem"
version = "1.0.0"
edition = "2024"
authors = ["AshyPingu"]
license = "GPL-3.0-or-later"

[dependencies]
cxx = "1.0.95"
cxx-qt = "0.8"
cxx-qt-lib = { version = "0.8", features = [ "qt_full"] }
knuffel = "3.2.0"
miette = { version = "7.6.0", features = ["fancy"] }
rand = "0.10.0"

[build-dependencies]
cxx-qt-build = { version = "0.8", features = [ "link_qt_object_files" ] }
# cxx-qt-build = "0.8"
